version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: ip -f inet addr show docker0 | grep -Po 'inet \K[\d.]+'
      - run: hostname -I
      - run: ls -l