version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker run -it --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=mydb -d -t mysql:8.0.23
      - run: echo 'export DB_HOST="$(ip -f inet addr show docker0 | grep -Po \"inet \K[\d.]+\"):3306"' >> $BASH_ENV
      - run: echo 'export DB_CONNECTION_URL="root:admin@${DB_HOST}/mydb"' >> $BASH_ENV
      - run: echo $DB_HOST
      - run: echo $DB_CONNECTION_URL
      - run: docker build -f Dockerfile-test -t rent-test .
      - run: docker run -it -v "$(pwd)/test-results":/home/app/test-results -e DB_HOST=$DB_HOST -e DB_CONNECTION_URL=$DB_CONNECTION_URL rent-test